### ISSUE TITLE
Maquetar cajas con mock

### ISSUE THREAD

**Issue by goncedillo** [Curso-Fullstack-Raul-Tejero/beauty-weather#8]
Crear maquetación contenido de días con info falsa.

**Días normales**

- [x] Icono pequeño
- [x] Fecha

**Día Hero**

- [x] Icono grande
- [x] Fecha
- [x] Índice de predicción
- [x] Temp máx
- [x] Temp min
- [x] Humedad

**Comment by RaulTejero** [comment]
Hechas las dos ramas en mobile

**Comment by goncedillo** [comment]
Se cierra cuando se mergee la rama 😉 lo que sí puedes hacer @RaulTejero es marcar las casillas como completas

**Comment by RaulTejero** [comment]
Ok
